apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  API_CLIENT_CREDENTIALS_ID: {{ .Values.secrets.API_CLIENT_ID | b64enc | quote }}
  API_CLIENT_CREDENTIALS_SECRET: {{ .Values.secrets.API_CLIENT_SECRET | b64enc | quote }}